import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./auth/authProvider";
import { ThemeProvider } from "./theme/themeProvider";
import { Sidebar } from "./_components/layout/sidebar";
import { HeaderMobile } from "./_components/layout/headerMobile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <ThemeProvider>
        <AuthProvider>
          <body className="flex flex-col md:flex-row">
            <HeaderMobile />
            <Sidebar />
            {children}
          </body>
        </AuthProvider>
      </ThemeProvider>
    </html>
  );
}
